---
title: "RSY: MC1"
subtitle: "Studiengang Data Science (HS2022), FHNW"
author: "Jan Zwicky und Gabriel Torres"
date: "Letzte Aktualisierungen: `r format(Sys.time(), '%B %d, %Y')`"
output:
  bookdown::html_document2:
      code_folding: show
      toc: true
      toc_depth: 3
      toc_float: true
      number_sections: true
editor_options: 
  chunk_output_type: console
---
<style>
#TOC {
  background-color: #F5F5F5;
  font-size: 16px;
}
#header{
  color: #708090;
  background-color: #F5F5F5;
  font-size: 30px;
}
body{
  color: #708090;
  background-color:#F5F5F5;
}
</style>

# Aufgabenstellung


# Daten aufbereiten und Pakete Lesen
## Pakete laden und Daten einlesen
### Pakete laden
```{r setup, cache = TRUE, message = FALSE, warning = FALSE}
# Pakete für Data wrangling und Visualisierung
library(tidyverse)

# Pakete für das HTML
library(bookdown)
library(knitr)

# Recommenderlab
library(recommenderlab)

# Latent Semantic Analysis
library(lsa)
```
###  Konfiguration
```{r}
# Konfiguration der Pakete
knitr::opts_chunk$set(fit.align = "left", cache = TRUE, warning = FALSE, message = FALSE)
set.seed(100)
```
### Daten einlesen
```{r}
# Einlesen der CSV-Dateien und erstellen der samples
movies <- read.csv("ml-latest-small/movies.csv", sep = ",")
links <- read.csv("ml-latest-small/links.csv", sep = ",")
ratings <- read.csv("ml-latest-small/ratings.csv", sep = ",")
tags <- read.csv("ml-latest-small/tags.csv", sep = ",")

# Sample von 70%
set.seed(69)
movies2 <- movies %>% slice_sample(prop = 0.7)
links2 <- subset(links, movieId %in% movies2$movieId)
ratings2 <- subset(ratings, movieId %in% movies2$movieId) %>% slice_sample(prop = 0.7)
tags2 <- subset(tags, movieId %in% movies2$movieId)

# 2ter Sample von 70%
set.seed(100)
movies <- movies %>% slice_sample(prop = 0.7)
links <- subset(links, movieId %in% movies$movieId)
ratings <- subset(ratings, movieId %in% movies$movieId) %>% slice_sample(prop = 0.7)
tags <- subset(tags, movieId %in% movies$movieId)
```
# 

```{r}
# M
sample_values <- sample(1:6819, 300, replace = FALSE)

norm_ratings <- ratings %>%
  group_by(userId) %>%
  summarise(mean_rating = mean(rating), sd_rating = sd(rating)) %>%
  full_join(., ratings, by = "userId")

norm_ratings$z_rating <- (norm_ratings$rating - norm_ratings$mean_rating) /
  norm_ratings$sd_rating

item_user_random_100 <- norm_ratings %>%
  select(movieId, userId, z_rating) %>%
  pivot_wider(names_from = userId, values_from = z_rating) %>%
  filter(movieId %in% sample_values) %>%
  head(100)
```

```{r}
calculate_similarity_cos <- function(arr1, arr2) {
  new_arr1 <- c()
  new_arr2 <- c()
  for (i in 2:length(arr1)) {
    if (!is.na(arr1[i]) & !is.na(arr2[i])) {
      new_arr1 <- append(new_arr1, arr1[i])
      new_arr2 <- append(new_arr2, arr2[i])
    }
  }
  cos_sim <- cosine(unlist(new_arr1), unlist(new_arr2))
  return(cos_sim)
}

predict_movie_rating <- function(user_item_matrix, userId, movie_Id, k) {
  all_movie_reviews <- user_item_matrix %>%
    filter(!is.na(.[userId + 1]))
  movie_to_rate <- user_item_matrix %>%
    filter(movieId == movie_Id)
  
  cos_sim <- c()
  for (index in 1:nrow(all_movie_reviews)) {
    cos_sim <- append(
      cos_sim,
      calculate_similarity_cos(movie_to_rate, all_movie_reviews[index, ])
    )
  }
  data <- data.frame(all_movie_reviews$movieId, all_movie_reviews[userId + 1], cos_sim)
  colnames(data) <- c("movieId", "userRating", "cosSim")
  data <- data %>% arrange(desc(cosSim)) %>% head(k)
  
  prediction <- sum(data$userRating * data$cosSim) / sum(data$cosSim)
  return(prediction)
}

predict_movie_rating(item_user_random_100, 1, 1093, 3)
```
